// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:url_launcher_app/models/item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ItemAdapter());
  }
}
